### ISSUE TITLE
错误的信号赋值没有报错提示

### ISSUE THREAD

**Issue by Devil-SX** [XS-MLVP/picker#19]
比如我的信号中是 io_a，正确修改应当是 `dut.io_a.value = `
但若写成 `dut.a  = `
不会有任何的报错提醒

**Comment by Devil-SX** [comment]
对于输出也是同理，比如 `if(dut.io_a == 1)` 这种逻辑不会报错，请求以上情况抛出 warnning 或者 error

**Comment by yaozhicheng** [comment]
> 对于输出也是同理，比如 `if(dut.io_a == 1)` 这种逻辑不会报错，请求以上情况抛出 warnning 或者 error

This is a fundamental feature of Python classes, enabling the overriding of instance variables. We will explore the necessity of issuing a warning for such overrides.

**Comment by yaozhicheng** [comment]
Thank you for your suggestion. The requirement has been implemented. An assertion check will be performed when attempting to override the pins in the DUT or when making a direct comparison. eg:
 
```bash
AssertionError: XPin Only support compare with XPin. Do you missed `.value`?
AssertionError: XPin and XData of DUT are read-only, do you mean to set the value of the signal? please use `a.value = ` instead.
```

Please reinstall the picker (need `make init`).

**Comment by Devil-SX** [comment]
Nice. Thanks for your time.
