### ISSUE TITLE
[BUG] `SubDataRef` incorrectly modifies other bits of XData

### ISSUE THREAD

**Issue by FrankOu2001** [XS-MLVP/picker#25]
## Description

`XData.SubDataRef` incorrectly modifies other bits of data

## Steps to Reproduce

Run the following code:

```python
from xspcomm import XData

if __name__ == '__main__':
    # SubDataRef Test
    data = XData(64, XData.InOut)
    ref1 = data.SubDataRef(40, 2)
    ref2 = data.SubDataRef(30, 6)
    ref1.value = 0b10
    expect_value = ref1.value
    ref2.value = 0xffff
    assert expect_value == ref1.value, "Value should be same"
```

## Expected Result

The result of `ref1.value` should be `0b10`.

## Actual Result

The result of `ref1.value` is  `0`.

## Screenshots

No screenshot

## Environment

- OS: Debian GNU/Linux bookworm 12.8 x86_64
- Version: 0.9.0-master-c67cbad-dirty

## Checklist

- [x] I have searched the existing issues
- [x] I have added the appropriate labels
- [x] I have reproduced the issue with the latest version
- [x] I have provided a detailed description of the bug
- [x] I have provided steps to reproduce the issue
- [x] I have included screenshots (if applicable)
- [x] I have provided the environment details (OS, version, etc.)

**Comment by yaozhicheng** [comment]
We have fixed the bug in the [xspcomm](https://github.com/XS-MLVP/xcomm) library. Please update the `xspcomm` library (uninstall the existing `xspcomm`, and then update the `xspcomm` code through `make init` in the picker project), and check if it works properly.
